version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    environment:
      - PYTHONPATH=/workspace
    ports:
      - "5001:5001"
    command: tail -f /dev/null  # Keep container running

  # Add any additional services your application needs here
  # For example, if you need a database:
  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: dify_jira
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: 